<a href="https://colab.research.google.com/github/KrisNguyen135/Deep-Learning-with-Google-Colab/blob/master/notebooks/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors - the data structure for deep learning

In [0]:
import torch

In [0]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [0]:
y = torch.tensor([
    [1, 2, 3],
    [2, 3, 4],
    [0, 0, 0]
])
y

tensor([[1, 2, 3],
        [2, 3, 4],
        [0, 0, 0]])

In [0]:
y = torch.tensor([
    [1, 2, 3],
    [2, 3, 4],
    [0, 0, 0]
], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])

In [0]:
torch.ones(1, 2, dtype=torch.int)

tensor([[1, 1]], dtype=torch.int32)

In [0]:
torch.zeros(5, 3, 2, dtype=torch.float)

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [0]:
z = torch.rand(3, 4, 2, dtype=torch.float)
z

tensor([[[0.4732, 0.5974],
         [0.2692, 0.8537],
         [0.0393, 0.4863],
         [0.0480, 0.1985]],

        [[0.5721, 0.9655],
         [0.2076, 0.2056],
         [0.0322, 0.0757],
         [0.3878, 0.0881]],

        [[0.4522, 0.9944],
         [0.0744, 0.3973],
         [0.6420, 0.1569],
         [0.4258, 0.8917]]])

In [0]:
y.size()

torch.Size([3, 3])

In [0]:
y[1]

tensor([2., 3., 4.])

In [0]:
y.size()[0]

3

In [0]:
print(y)
y[0]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([1., 2., 3.])

In [0]:
print(y)
y[:, 1]

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])


tensor([2., 3., 0.])

In [0]:
print(z)
z[2, :, 0]

tensor([[[0.4732, 0.5974],
         [0.2692, 0.8537],
         [0.0393, 0.4863],
         [0.0480, 0.1985]],

        [[0.5721, 0.9655],
         [0.2076, 0.2056],
         [0.0322, 0.0757],
         [0.3878, 0.0881]],

        [[0.4522, 0.9944],
         [0.0744, 0.3973],
         [0.6420, 0.1569],
         [0.4258, 0.8917]]])


tensor([0.4522, 0.0744, 0.6420, 0.4258])

In [0]:
y[:, :, 0]

IndexError: ignored

In [0]:
t = torch.rand(3, 3, dtype=torch.float)
t

tensor([[0.1555, 0.5022, 0.1621],
        [0.7351, 0.1005, 0.5153],
        [0.7838, 0.8149, 0.6233]])

In [0]:
y + t

tensor([[1.1555, 2.5022, 3.1621],
        [2.7351, 3.1005, 4.5153],
        [0.7838, 0.8149, 0.6233]])

In [0]:
y * t

tensor([[0.1555, 1.0044, 0.4863],
        [1.4703, 0.3015, 2.0610],
        [0.0000, 0.0000, 0.0000]])

In [0]:
y * 3

tensor([[ 3.,  6.,  9.],
        [ 6.,  9., 12.],
        [ 0.,  0.,  0.]])

In [0]:
y.view(1, 9)

tensor([[1., 2., 3., 2., 3., 4., 0., 0., 0.]])

In [0]:
y.view(-1,)

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [0]:
torch.squeeze(y.view(1, 9))

tensor([1., 2., 3., 2., 3., 4., 0., 0., 0.])

In [0]:
y.sum(0)

tensor([3., 5., 7.])

In [0]:
torch.max(y)

tensor(4.)

In [0]:
print(y)
values, indices = torch.max(y, 0)
print(values)
print(indices)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [0., 0., 0.]])
tensor([2., 3., 4.])
tensor([1, 1, 1])


In [0]:
y.numpy()

array([[1., 2., 3.],
       [2., 3., 4.],
       [0., 0., 0.]], dtype=float32)

In [0]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = torch.from_numpy(a)
b

tensor([[1, 2],
        [3, 4]])

In [0]:
a[0, 0] = 2
a

array([[2, 2],
       [3, 4]])

In [0]:
b

tensor([[2, 2],
        [3, 4]])

In [0]:
y[0, 0] == 1

tensor(1, dtype=torch.uint8)

# GPUs in Google Colab

In [0]:
import torch
import time

In [0]:
torch.cuda.is_available()

True

In [0]:
device = torch.device('cuda')

In [0]:
a = torch.ones(3, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [0]:
b = torch.ones(3, 3).to(device)
b

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [0]:
c = torch.ones(3, 3).cuda()
c

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [0]:
start = time.time()
a = torch.ones(400, 400)
for _ in range(10000):
    a += a
duration = time.time() - start
print(f'CPU time: {duration}')

start = time.time()
b = torch.ones(400, 400).to(device)
for _ in range(10000):
    b += b
duration = time.time() - start
print(f'GPU time: {duration}')


CPU time: 0.22700166702270508
GPU time: 0.08193254470825195


In [0]:
b

tensor([[inf, inf, inf,  ..., inf, inf, inf],
        [inf, inf, inf,  ..., inf, inf, inf],
        [inf, inf, inf,  ..., inf, inf, inf],
        ...,
        [inf, inf, inf,  ..., inf, inf, inf],
        [inf, inf, inf,  ..., inf, inf, inf],
        [inf, inf, inf,  ..., inf, inf, inf]], device='cuda:0')

In [0]:
!ln -sf /opt/bin/nvidia-smi /usr/bin/nvidia-smi
!pip install gputil
!pip install psutil
!pip install humanize
import psutil
import humanize
import os
import GPUtil as GPU
GPUs = GPU.getGPUs()
# XXX: only one GPU on Colab and isn’t guaranteed
gpu = GPUs[0]

  Stored in directory: /root/.cache/pip/wheels/3d/77/07/80562de4bb0786e5ea186911a2c831fdd0018bda69beab71fd
Successfully built gputil


In [0]:
def printm():
    process = psutil.Process(os.getpid())
    print("Gen RAM Free: " + humanize.naturalsize( psutil.virtual_memory().available ), " | Proc size: " + humanize.naturalsize( process.memory_info().rss))
    print("GPU RAM Free: {0:.0f}MB | Used: {1:.0f}MB | Util {2:3.0f}% | Total {3:.0f}MB".format(gpu.memoryFree, gpu.memoryUsed, gpu.memoryUtil*100, gpu.memoryTotal))
    
printm()

Gen RAM Free: 12.9 GB  | Proc size: 150.2 MB
GPU RAM Free: 15079MB | Used: 0MB | Util   0% | Total 15079MB
